stages:
  - unit
  - e2e
  - deploy


Unit_Test:
  stage: unit
  image: node:latest
  tags:
    - editor
    - test
  only:
    - master
    - dev
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm test

End_To_End:
  stage: e2e
  image: cypress/browsers:node12.14.1-chrome85-ff81
  tags:
    - editor
    - test
    - e2e

  only:
    - master
    - dev
  script:
    - npm install
    - npm start &
    - npm run cypress:run -- --browser chrome
    - npm run cypress:run -- --browser firefox
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

Build:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
  image: node:latest
  tags:
    - editor
    - build
  only:
    - master
  cache:
    paths:
      - node_modules/
  before_script:
    # Register the contents of the SSH_PRIVATE_KEY variable to the agent store
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - gitlab_hostname=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@||g' | sed -e 's|/.*||g')
    - ssh-keyscan "${gitlab_hostname}" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    
    # Remember to set up user informantion for the git commands to work.
    - git config --global user.email "email@example.com"
    - git config --global user.name "CI Runner"
  script:
    - npm install
    - npm run build # build directly into submodule directory
    - cd konekoe-editor-release/
    - git add konekoe-editor.js
    - git commit -m "Build on $CI_COMMIT_TIMESTAMP"
    - LATEST_COMMIT=$(git log -1 --format=format:"%H")
    - git checkout master
    - git merge $LATEST_COMMIT
    - url_host=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@|ssh://git@|g')
    - git remote set-url --push origin "${url_host}"
    - git push origin master