stages:
  - unit
  - e2e
  - deploy


Unit_Test:
  stage: unit
  image: node:latest
  tags:
    - editor
    - test
  only:
    - master
    - dev
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm test

End_To_End:
  stage: e2e
  image: cypress/browsers:node12.14.1-chrome85-ff81
  tags:
    - editor
    - test
    - e2e

  only:
    - master
    - dev
  script:
    - npm install
    - npm start &
    - sleep 60 # Wait awhile so that the project can be built before the test are run
    - npm run cypress:run -- --browser chrome
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

Build:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
  image: node:latest
  tags:
    - editor
    - build
  only:
    - master
  cache:
    paths:
      - node_modules/
  before_script:
    # Register the contents of the SSH_PRIVATE_KEY variable to the agent store
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    # Create .ssh with the correct permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Set up known_hosts. Required for host verification.
    - gitlab_hostname=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@||g' | sed -e 's|/.*||g')
    - ssh-keyscan "${gitlab_hostname}" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    
    # Remember to set up user informantion for the git commands to work.
    - git config --global user.email "email@example.com"
    - git config --global user.name "CI Runner"
  script:
    - npm install
    - cd konekoe-editor-release/
    - git checkout master
    - cd ../
    - npm run build # build directly into submodule directory
    - cd konekoe-editor-release/
    - git add konekoe-editor.js
    - git commit -m "Built from ${CI_COMMIT_SHA}"
    # By default, Gitlab CI uses https. Explicitly set remote to utilize ssh and the deploy key set up in the before_script. 
    - git remote set-url --push origin "git@version.aalto.fi:konekoe/konekoe-editor-release.git"
    - git push
