stages:
  - unit
  - e2e
  - deploy


Unit_Test:
  stage: unit
  image: node:latest
  tags:
    - editor
    - test
  only:
    - master
    - dev
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm test

End_To_End:
  stage: e2e
  image: cypress/browsers:node12.14.1-chrome85-ff81
  tags:
    - editor
    - test
    - e2e

  only:
    - master
    - dev
  script:
    - npm install
    - npm start &
    - npm run cypress:run -- --browser chrome
    - npm run cypress:run -- --browser firefox
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

Build:
  stage: build
  image: node:latest
  tags:
    - editor
    - build
  only:
    - master
  cache:
    paths:
      - node_modules/
  before_script:
    # Install ssh-agent and add the content of the SSH_PRIVATE_KEY variable to the agent store
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Remember to set up user informantion for the git commands to work.
    - git config --global user.email "user@example.com"
    - git config --global user.name "User name"
  script:
    - npm install
    - npm run build
    - cd konekoe-editor-release/
    - git add konekoe-editor.js
    - git commit -m "Build on $CI_COMMIT_TIMESTAMP"
    - git push
